#!/bin/bash
# Cloud-init bootstrap for the LobeChat EC2 instance.
# Stage 1: Docker + Compose + AWS CLI.
# Stage 2: clone repo, generate .env, fetch traefik.me cert, bring up stack.
set -euxo pipefail

# Variables injected by Terraform (templatefile)
AWS_REGION="${aws_region}"
PUBLIC_HOSTNAME="${public_hostname}"
AUTH_HOSTNAME="${auth_hostname}"
S3_HOSTNAME="${s3_hostname}"
REPO_URL="${repo_url}"
REPO_REF="${repo_ref}"

# Log everything to a known file for debugging via SSH.
exec > >(tee /var/log/bootstrap.log) 2>&1

echo "=== bootstrap start: $(date -u +%FT%TZ) ==="
echo "region:   $AWS_REGION"
echo "lobe:     $PUBLIC_HOSTNAME"
echo "auth:     $AUTH_HOSTNAME"
echo "s3:       $S3_HOSTNAME"
echo "repo:     $REPO_URL @ $REPO_REF"

export DEBIAN_FRONTEND=noninteractive

# ----------------------------------------------------------------------
# Stage 1: Docker, Compose, AWS CLI
# ----------------------------------------------------------------------

apt-get update -y
apt-get install -y --no-install-recommends \
    ca-certificates curl gnupg jq unzip git make openssl

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable" \
    > /etc/apt/sources.list.d/docker.list

apt-get update -y
apt-get install -y --no-install-recommends \
    docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

systemctl enable --now docker
usermod -aG docker ubuntu

cd /tmp
curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscli.zip
unzip -q awscli.zip
./aws/install
rm -rf aws awscli.zip
cd /

echo "=== stage 1 done: $(date -u +%FT%TZ) ==="
docker --version
docker compose version
/usr/local/bin/aws --version
/usr/local/bin/aws --region "$AWS_REGION" sts get-caller-identity

# ----------------------------------------------------------------------
# Stage 2: app deploy
# ----------------------------------------------------------------------

APP_DIR=/opt/lobechat
ENV_FILE=$APP_DIR/.env

git clone --branch "$REPO_REF" --depth 1 "$REPO_URL" "$APP_DIR"
chown -R ubuntu:ubuntu "$APP_DIR"

# Caddy issues a Let's Encrypt cert at startup for $PUBLIC_HOSTNAME using
# HTTP-01. Just create the data dirs so Caddy can persist its acme state.
mkdir -p "$APP_DIR/data/caddy/data" "$APP_DIR/data/caddy/config"

# Rewrite Casdoor URLs to our public HTTPS hostnames.
# 47000 → LobeChat (PUBLIC_HOSTNAME); 47002 → Casdoor (AUTH_HOSTNAME).
mkdir -p "$APP_DIR/data/casdoor"
sed \
    -e "s|http://wsl.ymbihq.local:47000|https://$PUBLIC_HOSTNAME|g" \
    -e "s|http://wsl.ymbihq.local:47002|https://$AUTH_HOSTNAME|g" \
    -e "s|http://localhost:3210|https://$PUBLIC_HOSTNAME|g" \
    "$APP_DIR/config/init_data.json" > "$APP_DIR/data/casdoor/init_data.json"

# Casdoor's app.conf origin field defines the absolute-URL base it bakes
# into OAuth metadata + redirects.
sed -i \
    -e "s|origin = http://wsl.ymbihq.local:47002|origin = https://$AUTH_HOSTNAME|g" \
    "$APP_DIR/config/casdoor-app.conf"

# Generate .env with random secrets. NOTE: this is a deliberate spec deviation
# (sandbox role denies SSM + secretsmanager:CreateSecret). Documented in REPORT.md.
KEY_VAULTS_SECRET=$(openssl rand -base64 32 | tr -d '\n')
NEXT_AUTH_SECRET=$(openssl rand -base64 32 | tr -d '\n')
POSTGRES_PASSWORD=$(openssl rand -hex 16)
MINIO_ROOT_USER=lobechat
MINIO_ROOT_PASSWORD=$(openssl rand -hex 16)
LITELLM_MASTER_KEY="sk-$(openssl rand -hex 24)"

# Casdoor's seeded init_data.json includes an OAuth application named
# "lobechat". Extract its client credentials so LobeChat's NextAuth config
# matches what Casdoor expects.
AUTH_CASDOOR_ID=$(jq -r '.applications[] | select(.name=="lobechat") | .clientId' "$APP_DIR/data/casdoor/init_data.json" | head -1)
AUTH_CASDOOR_SECRET=$(jq -r '.applications[] | select(.name=="lobechat") | .clientSecret' "$APP_DIR/data/casdoor/init_data.json" | head -1)

cat > "$ENV_FILE" <<EOF
# Generated by user_data.sh on $(date -u +%FT%TZ). Do not commit.
HOST_DOMAIN_LOBE=$PUBLIC_HOSTNAME
HOST_DOMAIN_AUTH=$AUTH_HOSTNAME
HOST_DOMAIN_S3=$S3_HOSTNAME
AWS_REGION=$AWS_REGION
AWS_DEFAULT_REGION=$AWS_REGION

# Random secrets
KEY_VAULTS_SECRET=$KEY_VAULTS_SECRET
NEXT_AUTH_SECRET=$NEXT_AUTH_SECRET
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Casdoor SSO (from seeded init_data.json)
AUTH_CASDOOR_ID=$AUTH_CASDOOR_ID
AUTH_CASDOOR_SECRET=$AUTH_CASDOOR_SECRET

# MinIO
MINIO_ROOT_USER=lobechat
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
S3_BUCKET=lobe

# LiteLLM master key (LobeChat sends, LiteLLM validates)
LITELLM_MASTER_KEY=$LITELLM_MASTER_KEY

# MCPHub: SSH config left empty in this deploy (no ssh-exec target).
SSH_HOST=
SSH_PORT=22
SSH_USERNAME=
SSH_ALLOWED_COMMANDS=
SSH_ALLOWED_PATHS=
SSH_COMMANDS_BLACKLIST=
SSH_ARGUMENTS_BLACKLIST=
OPENAPI_MCP_HEADERS=
EOF

chmod 0600 "$ENV_FILE"
chown ubuntu:ubuntu "$ENV_FILE"

# Pre-create data dirs so docker compose doesn't create them as root.
mkdir -p "$APP_DIR/data"/{postgres,minio,qdrant,mcphub,caddy/data,caddy/config}
mkdir -p "$APP_DIR/config/ssh"
chown -R ubuntu:ubuntu "$APP_DIR/data" "$APP_DIR/config/ssh"

# Bring up the stack as ubuntu (uses the docker group membership).
cd "$APP_DIR"
sudo -u ubuntu docker compose --env-file "$ENV_FILE" up -d --build

# Wait for MinIO healthcheck then create the LobeChat bucket. LobeChat
# uploads fail if the bucket does not exist on first use.
echo "=== waiting for minio healthcheck before bucket setup ==="
for i in $(seq 1 30); do
  if sudo -u ubuntu docker inspect --format '{{.State.Health.Status}}' minio 2>/dev/null | grep -q healthy; then
    break
  fi
  sleep 5
done
sudo -u ubuntu docker exec minio mc alias set local http://localhost:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" || true
sudo -u ubuntu docker exec minio mc mb -p local/lobe || true
sudo -u ubuntu docker exec minio mc anonymous set download local/lobe || true

echo "=== bootstrap done: $(date -u +%FT%TZ) ==="
echo "Stack should be reachable at https://$PUBLIC_HOSTNAME within a few minutes."
echo "Tail logs: docker compose logs -f lobe-chat"
